### ISSUE TITLE
Mainboard, mystery component?

### ISSUE THREAD

**Issue by kawong22** [IBM/MicroscoPy#10]
Hello.
I'm looking at the Instructions.pdf page Electronics - Mainboard.  On the picture of the Mainboard, there is an unlabeled black capacitor(?) on the Mainboard to the left of the LED driver.  Does this component need to be soldered on?  What is it and its specifications?  Do you have a part number for it? 
Thank you!
Keith

**Comment by yukseltemiz** [comment]
Hi Keith, sorry I saw your message just now. I had a separate pdf file explaining more details about the electronics: https://github.com/IBM/MicroscoPy/blob/master/Circuit/CircuitAssembly.pdf 

I think the answer should be there but briefly that capacitor is needed for the PWM function of the LED driver. It's in the datasheet of the driver. https://recom-power.com/pdf/Lightline_DC-DC/RCD-24_PL.pdf 

Let me know if this does not help. 
Best,
Yuksel

**Comment by kawong22** [comment]
Thanks! got it.  somehow missed that doc.
