### ISSUE TITLE
stacking photo ?

### ISSUE THREAD

**Issue by dimgod59** [IBM/MicroscoPy#6]
hi, 
can we stack the photos? to have a better image depth

**Comment by yukseltemiz** [comment]
Hi, I think it's possible and would be useful. Thanks for the suggestion, I thought about this before, in principle we can slowly change the focus and capture images, I know there are several algorithms available in Python, it's not my area of expertise but I can give it a try and update the repo.

**Comment by thalesfsp** [comment]
@yukseltemiz That would be great! By the way, it's such a great and important (giving the current world situation) project! Congrats for the team that worked on that!
