### ISSUE TITLE
BoM and lenses

### ISSUE THREAD

**Issue by thalesfsp** [IBM/MicroscoPy#7]
Hello, :) It would be great if the project had a BoM (Bill of Materials), with links (to the recommended items), and specifications. This would help, and make it easier for people to buy the required items and do the project. Regarding the lenses, what other options do you recommend (high-quality ones) besides the [TREEYE 15.3mm lens M12](https://www.aliexpress.com/i/32879460954.html)? What other lens do you recommend for the HQ-camera? Cheers!

**Comment by yukseltemiz** [comment]
Hi. Thanks for the suggestion. I have a detailed BoM with the weblinks but it was in the long instruction manual, page #71 https://github.com/IBM/MicroscoPy/blob/master/Instructions.pdf

I just added it to the main page  as well. https://github.com/IBM/MicroscoPy/blob/master/Bill%20of%20Materials%20(BOM).pdf

I did not test any other lens with this microscope. [Thorlabs ](https://www.thorlabs.com/navigation.cfm?guide_id=2027) for example have good microscope lenses but they could be too heavy for the tilting stage. Or you could try something like [this,](https://www.banggood.com/HAYEAR-5X-120X-Industrial-Zoom-Lens-for-Digital-Microscope-Camera-C-Mount-Lens-with-High-Working-Distance-p-1449515.html?rmmds=search&cur_warehouse=CN) the HQ camera has a C mount adapter, so you should be able to connect directly.

**Comment by hucik14** [comment]
@thalesfsp have you tried any better lens? I have exactly the same as in the description of this project and I would like to achieve even higher magnification. I wonder how would this one work - [https://www.aliexpress.com/item/32818045696.html](https://www.aliexpress.com/item/32818045696.html) - but I'm afraid that 2 megapixel resolution might be a problem, but maybe not - it is glass so the number is maybe related more to quality than to actual resolution of a lens.

**Comment by yukseltemiz** [comment]
Hi,

Thanks for your message. 

No, I haven't tried a better lens but I've tried Raspberry Pi's HQ camera, 
https://github.com/IBM/MicroscoPy/tree/master/HQ-camera

I had better resolution and color reproducibility with the HQ camera, so 
maybe you can gain a little bit of additional magnification by digital 
zooming, but I think it wouldn't be too significant.

I am aware of this X megapixel spec on these M12 lenses but honestly I 
don't know what it represents. I don't have much (or any) experience in 
optics, this project was a hobby for me. 

You may consider better quality lenses from Thorlabs or Edmund Optics, 
etc. maybe.

Sorry that I couldn't help much.

Best regards,
Yuksel

--------------------------------------------------------------------------------
Yuksel Temiz, Ph.D.
Research Staff Member, Precision Diagnostics
IBM Research - Zurich
Phone: (+41 44) 724 8063 
https://www.zurich.ibm.com/st/precision_diagnostics/

**Comment by hucik14** [comment]
Hi, thank you for your reply :)) the Thorlabs and Edmund Optics lenses looks so good but a bit over budget 😄 I will probably try some lens as I posted before. If I get any results I will share it here.

**Comment by dematoine** [comment]
@hucik14 did you try any of the lenses above? Could you update us with the results? :)

**Comment by hucik14** [comment]
I haven't tried anything different so far, but I still plan to... hopefully I will have time during Christmas holidays. If I have any (even bad) results, I will share it here.

**Comment by harundurmush** [comment]
Hi, can you provide me the references for your optical system? Or an explanation for why did we take the Raspberry Pi camera's lens out?

**Comment by hucik14** [comment]
You remove the original lens and put an external one in bigger distance. Read more on _extension tubes in macro photography_, for example here: 
https://shuttermuse.com/ultimate-guide-to-extension-tubes/

**Comment by hucik14** [comment]
> I haven't tried anything different so far, but I still plan to... hopefully I will have time during Christmas holidays. If I have any (even bad) results, I will share it here.

Sorry I forgot to comment on this - I tried a better lenses, the quality of the images improved a bit, but I was not able to get higher zoom.

**Comment by harundurmush** [comment]
Thanks for your help :)

**Comment by yukseltemiz** [comment]
Hi. I am the designer of the microscope, but I left IBM a few years ago, so the repository is not maintained anymore. 

Regarding the question about the lens, I agree with the previous user's reply. 

I will do my best to answer other questions but it's been a while, I may not remember all the details :-)

**Comment by harundurmush** [comment]
Thank you for your return. I think the instructions are very enough to actualize the project, with all my respect. I am just having a hard time about recreating an alternative version of the optical part, specifically about enough magnification for medical histology.

**Comment by yukseltemiz** [comment]
Thanks. Achieving higher magnification with this single lens configuration can be difficult, and anyway, the resolution will be limited by diffraction. I founded my own company on microscopy, please feel free to check and contact me to learn more: https://www.microqubic.com/ Best regards.
