### ISSUE TITLE
Information for printing PCBs

### ISSUE THREAD

**Issue by jtabernik** [IBM/MicroscoPy#8]
I am trying to get a quote for printing the PCBs.  Unfortunately, I don't know much about PCBs so the options are very confusing to me (layer count, material type, FR4-TG, thickness, finished copper, min spacing, min hole size, surface finish, etc. etc.--example from a vendor is attached).

Is there somewhere I can get more information to answer these questions for a PCB printing service?  Also, if you or someone else can supply me with the correct responses, I can document this for your project so others will know what to do as well.

Thank you so much for sharing your knowledge on this!  Not only an amazing project, the final result will be incredibly useful!  Thank you!

![image](https://user-images.githubusercontent.com/412300/90944230-75b77b00-e3eb-11ea-98d1-26107f67cbea.png)

**Comment by yukseltemiz** [comment]
Hi, really sorry for my late response, I was on holidays and then didn't see your message. I hope it's not too late but https://jlcpcb.com/ is a good one. Just use everything default, upload the Gerber zip files (https://github.com/IBM/MicroscoPy/tree/master/Circuit) and that's it. I think the system calculates the dimensions and the rest automatically, they will check your design and start the manufacturing, it should cost a few dollars for 5-10 units + shipping.  I used the exact files for my prototypes, so should be fine. Please let me know if it does not work. Thank you for your nice comments and again apologies for being late to respond. Best regards. Yuksel

**Comment by jtabernik** [comment]
No problem and thank you so much!!!!
